name: donaciones
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sidebarx: ^0.16.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
